swagger: '2.0'
basePath: /gotapi/camera
info:
  title: Camera Profile
  version: 2.0.0
  description: スマートデバイス(Cameraデバイスなど）のズーム操作機能を提供するAPI。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /zoom:
    get:
      operationId: cameraZoomGet
      x-type: one-shot
      summary: Cameraデバイスの現在の倍率を取得する。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CameraGetZoomResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              zoomPosition: 0
    put:
      operationId: cameraZoomPut
      x-type: one-shot
      summary: Cameraデバイスに対してレンズのズームイン・アウトリクエストを送る。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: direction
          description:  >-
            方向。ズームの方向<br>
            in<br>
            out
          in: formData
          required: true
          type: string
          enum:
            - in
            - out
        - name: movement
          description: >-
            動作。ズームの動作<br>in-startで開始して
            in-stopで終了。<br>1shotは開始してから所定位置まで動作する。<br>maxはin-startと同じ動作を行う。
          in: formData
          required: true
          type: string
          enum:
            - in-start
            - in-stop
            - 1shot
            - max
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/CameraSetZoomResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
definitions:
  CameraGetZoomResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - type: object
        required:
          - zoomPosition
        properties:
          zoomPosition:
            type: number
            title: カメラの倍率
            description: >-
              カメラの倍率(%)<br>
              例)<br>
              QX-10の場合<br>
              0(%):拡大なし<br>
              50(%):倍率5倍での拡大
  CameraSetZoomResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: '0: 正常応答<br>0以外: 異常応答'
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。
