swagger: '2.0'
basePath: /gotapi/driveController
info:
  title: DriveController Profile
  version: 2.0.0
  description: スマートデバイスの駆動処理を提供するAPI。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /move:
    post:
      operationId: driveControllerMovePost
      x-type: one-shot
      summary: スマートデバイスを指定された方向に移動開始する。
      description: >-
        デバイスが動作する方向のキャリブレーションなどに関しては、
        デバイスの仕様により変わってくる。
        speedが指定されていない場合は移動を行わないこと。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: angle
          description: >-
            角度。デバイスの方向 (degree)<br>
            0~360
          in: formData
          required: true
          type: number
          minimum: 0
          maximum: 360
        - name: speed
          description: >-
            速度。デバイスの動く速度<br>
            0.0~1.0
          in: formData
          required: true
          type: number
          minimum: 0
          maximum: 1
      responses:
        '200':
          description: >-
            移動開始が成功したかどうかの結果を返す。
            移動開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/DriveControllerMoveResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
  /stop:
    delete:
      operationId: driveControllerStopDelete
      x-type: one-shot
      summary: スマートデバイスに移動停止リクエストを送る。
      description: >-
        すでにスマートデバイスが移動停止している場合に、
        移動停止リクエストが送られた場合は、エラーを返すことが望ましい。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            移動停止リクエストの結果を返す。
            移動停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/DriveControllerStopResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
  /rotate:
    put:
      operationId: driveControllerRotatePut
      x-type: one-shot
      summary: スマートデバイスを指定された向きに回転を行う。
      description: >-
        デバイスが動作する角度のキャリブレーションなどに関しては、
        デバイスの仕様により変わってくる。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: angle
          description: >-
            角度。デバイスの方向 (degree)<br>
            0~360
          in: formData
          required: true
          type: number
          minimum: 0
          maximum: 360
      responses:
        '200':
          description: >-
            回転が成功したかどうかの結果を返す。
            失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/DriveControllerRotateResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
definitions:
  DriveControllerMoveResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  DriveControllerStopResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  DriveControllerRotateResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: >-
          0: 正常応答<br>
          0以外: 異常応答
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: >-
          レスポンスに対する署名。
          アプリケーション側から事前にHMACキーを共有されていた場合は必須。
