swagger: '2.0'
basePath: /gotapi/files
info:
  title: Files Profile
  version: 2.0.0
  description: >-
    各デバイスプラグインが持っているファイルにアクセスするためのAPI。<br>
    Javascriptからは、バイナリを直接操作することができない。<br>
    その為にURIという形にして返却することになる。<br>
    その為にFile Receive APIでファイルを取得する際には、
    Filesプロファイルを経由して取得できるURIにしている。<br>
    例えば、Javascriptでは、取得したURIが画像の場合には、
    imgタグのsrcに設定して画像を表示する。<br>
    テキストの場合には、XMLHttpRequestでテキストを取得する。
consumes: []
paths:
  /:
    get:
      operationId: filesGet
      x-type: one-shot
      summary: 各デバイスプラグインが持っているファイルにアクセスする。
      description: >-
        基本的にこのプロファイルを使用することはできない。
        DeviceConnectManagerなどで内部的に使用しているプロファイルである。
      parameters:
        - name: uri
          description: リソースのURL。デバイスプラグインが持つファイルのURI。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            バイナリーデータが直接返ってくる。<br>
            FileProfileなどで設定したファイルにより、ファイルのタイプなどが変わってくる。
