swagger: '2.0'
basePath: /gotapi/proximity
info:
  title: Proximity Profile
  version: 2.0.0
  description: スマートデバイスの近接センサーの物/人の検知を通知するAPI。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /onDeviceProximity:
    get:
      operationId: proximityOnDeviceProximityGet
      x-type: one-shot
      summary: スマートデバイスの近接センサーが物体を検知した値を取得する。
      description: >-
        スマートデバイスの近接センサーの情報を
        近接距離最小/最大値の範囲で連続的にイベント発行する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            近接センサーの値を返す。
            センサーの値の取得に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/DeviceProximityResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              proximity:
                value: 12.3456
                min: 1.23456
                max: 123.456
                threshold: 12.3456
                range: NEAR
    put:
      operationId: proximityOnDeviceProximityPut
      x-type: event
      summary: スマートデバイスの近接センサーが物体を検知したことを通知するイベントを開始する。
      description: >-
        スマートデバイスの近接センサーの情報を
        近接距離最小/最大値の範囲で連続的にイベント発行する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: interval
          description: デバイスプラグインがイベントを送信する間隔。
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: >-
            近接センサーの物体を検知したイベントの開始結果を返す。
            開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/DeviceProximityEvent'
        examples:
          application/json:
            serviceId: Host.exampleId.localhost.deviceconnect.org
            profile: proximity
            attribute: ondeviceproximity
            proximity:
              value: 12.3456
              min: 1.23456
              max: 123.456
              threshold: 12.3456
              range: NEAR
    delete:
      operationId: proximityOnDeviceProximityDelete
      x-type: event
      summary: スマートデバイスの近接センサーが物体を検知したことを通知するイベントを停止する。
      description: >-
        スマートデバイスの近接センサーの情報を
        近接距離最小/最大値の範囲で連続的にイベント発行する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            近接センサーの物体を検知したイベントの停止結果を返す。
            停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/DeviceProximityEvent'
  /onUserProximity:
    get:
      operationId: proximityOnUserProximityGet
      x-type: one-shot
      summary: スマートデバイスの近接センサーが人体を検知した値を取得する。
      description: >-
        ユーザ検知とは、例えば通話時にスマートフォンの画面を耳元に近接させた場合等に
        発生する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            近接センサーの値を返す。
            センサーの値の取得に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/UserProximityResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              proximity:
                near: true
    put:
      operationId: proximityOnUserProximityPut
      x-type: event
      summary: スマートデバイスの近接センサーが人体を検知したことを通知するイベントを開始する。
      description: >-
        ユーザ検知とは、例えば通話時にスマートフォンの画面を耳元に近接させた場合等に
        発生する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: interval
          description: デバイスプラグインがイベントを送信する間隔。
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: >-
            近接センサーの人体を検知したイベントの開始結果を返す。
            開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/UserProximityEvent'
        examples:
          application/json:
            serviceId: Host.exampleId.localhost.deviceconnect.org
            profile: proximity
            attribute: onuserproximity
            proximity:
              near: true
    delete:
      operationId: proximityOnUserProximityDelete
      x-type: event
      summary: スマートデバイスの近接センサーの人体を検知したことを通知するイベントを停止する。
      description: >-
        ユーザ検知とは、例えば通話時にスマートフォンの画面を耳元に近接させた場合等に
        発生する。
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            近接センサーの人体を検知したイベントの停止結果を返す。
            停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/UserProximityEvent'
definitions:
  DeviceProximityEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/DeviceProximityInfo'
  DeviceProximityResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/DeviceProximityInfo'
  DeviceProximityInfo:
    type: object
    required:
      - proximity
    properties:
      proximity:
        type: object
        title: 近接イベント
        properties:
          value:
            type: integer
            title: 近接距離
            description: cm単位の距離。
          min:
            type: integer
            title: 近接距離最小値
            description: cm単位の距離。
          max:
            type: integer
            title: 近接距離最大値
            description: cm単位の距離。
          threshold:
            type: integer
            title: 閾値
            description: cm単位の距離の閾値。
          range:
            type: string
            title: 距離識別子
            description: 距離を示す文字列。
            enum:
              - IMMEDIATE
              - NEAR
              - FAR
              - UNKNOWN
  UserProximityEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/UserProximityInfo'
  UserProximityResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/UserProximityInfo'
  UserProximityInfo:
    type: object
    required:
      - proximity
    properties:
      proximity:
        type: object
        title: 近接イベント
        required:
          - near
        properties:
          near:
            type: boolean
            title: 近接の有無
            description: >-
              ユーザがデバイスに近接しているかどうか。<br>
              true: 近接している<br>
              false: 近接していない'
  EventRegistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  EventUnregistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: >-
          0: 正常応答<br>
          0以外: 異常応答
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: >-
          レスポンスに対する署名。<br>
          アプリケーション側から事前にHMACキーを共有されていた場合は必須。
  CommonEvent:
    type: object
    required:
      - serviceId
      - profile
      - interface
      - attribute
    properties:
      serviceId:
        type: string
        title: サービスID
        description: イベントを送信したサービスのID
      profile:
        type: string
        title: プロファイル名
        description: プロファイル名。
      interface:
        type: string
        title: インターフェース名
        description: インターフェース名。
      attribute:
        type: string
        title: アトリビュート名
        description: アトリビュート名。
