swagger: '2.0'
basePath: /gotapi/remoteController
info:
  title: Remote Controller Profile
  version: 2.0.0
  description: スマートデバイスが保持する赤外線などの信号の送受信機能を提供するAPI。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /:
    get:
      operationId: remoteControllerGet
      x-type: one-shot
      summary: スマートデバイスが保持する赤外線などの信号を取得する。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/ReceiveRemoteControllerResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              message: >-
                {data[18031,8755,1190,1190,1190,3341,1190,3341,1190,3341,1190,1190,
                1190,3341,1190,3341,1190,3341,1190,3341,1190,3341,1190,3341,1190,
                1190,1190,1190,1190,1190,1190,1190,1190,3341,1190,3341,1190,1190,
                1190,3341,1190,1190,1190,1190,1190,1190,1190,1190,1190,1190,1190,
                1190,1190,1190,1190,1190,1190,3341,1190,3341,1190,3341,1190,3341,
                1190,3341,1190,65535,0,9379,18031,4400,1190]}
    post:
      operationId: remoteControllerPost
      x-type: one-shot
      summary: スマートデバイスに対して赤外線などの信号送信依頼を送る。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: message
          description: メッセージ(赤外線など)。赤外線などの信号。
          in: formData
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/SendRemoteControllerResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
definitions:
  ReceiveRemoteControllerResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - type: object
        required:
          - message
        properties:
          message:
            type: string
            title: メッセージ(赤外線など）
            description: 赤外線などの信号。
  SendRemoteControllerResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: '0:正常応答<br>0以外:異常応答'
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: >-
          レスポンスに対する署名。
          アプリケーション側から事前にHMACキーを共有されていた場合は必須。
