swagger: '2.0'
basePath: /gotapi/sphero
info:
  title: Sphero Profile
  version: 2.0.0
  description: Spheroに搭載されているセンサーの値を通知するプロファイル。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /quaternion/onQuaternion:
    get:
      operationId: spheroQuaternionOnQuaternionGet
      x-type: one-shot
      summary: Spheroの四元数を通知するイベントを取得する。
      description: プラグイン側でキャッシュしている最新のイベントメッセージを1つ取得する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの四元数を返す。取得できない場合はエラーを返す。
          schema:
            $ref: '#/definitions/QuaternionResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              quaternion:
                q0: 0.9998000264167786
                q1: -0.0027000000700354576
                q2: -0.010099999606609344
                q3: 0.010900000110268593
                interval: 220
    put:
      operationId: spheroQuaternionOnQuaternionPut
      x-type: event
      summary: Spheroの四元数を通知するイベントの受信を開始する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: formData
          required: true
          type: string
        - name: interval
          description: イベント受信間隔。単位：mSec
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: >-
            Spheroの四元数を通知するイベントの開始結果を返す。
            開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/QuaternionEvent'
        examples:
          application/json:
            serviceId: Host.exampleId.localhost.deviceconnect.org
            profile: sphero
            interface: quaternion
            attribute: onquaternion
            quaternion:
              q0: 0.9998000264167786
              q1: -0.0027000000700354576
              q2: -0.010099999606609344
              q3: 0.010900000110268593
              interval: 220
    delete:
      operationId: spheroQuaternionOnQuaternionDelete
      x-type: event
      summary: Spheroの四元数を通知するイベントの受信を停止する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの四元数を通知するイベントの停止結果を返す。
            停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
  /locator/onLocator:
    get:
      operationId: spheroLocatorOnLocatorGet
      x-type: one-shot
      summary: Spheroの位置と速度を通知するイベントを取得する。
      description: プラグイン側でキャッシュしている最新のイベントメッセージを1つ取得する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの位置と速度を返す。位置と速度の取得に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/LocatorResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              locator:
                positionX: -3
                positionY: 5
                velocityX: -10
                velocityY: -1.5
    put:
      operationId: spheroLocatorOnLocatorPut
      x-type: event
      summary: Spheroの位置と速度を通知するイベントの受信を開始する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: formData
          required: true
          type: string
        - name: interval
          description: イベント受信間隔。単位：mSec
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: >-
            Spheroの位置と速度を通知するイベントの開始結果を返す。
            開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/LocatorEvent'
        examples:
          application/json:
            serviceId: Host.exampleId.localhost.deviceconnect.org
            profile: sphero
            interface: locator
            attribute: onlocator
            locator:
              positionX: -3
              positionY: 5
              velocityX: -10
              velocityY: -1.5
    delete:
      operationId: spheroLocatorOnLocatorDelete
      x-type: event
      summary: Spheroの位置と速度を通知するイベントの受信を停止する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの位置と速度を通知するイベントの停止結果を返す。
            停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
  /collision/onCollision:
    get:
      operationId: spheroCollisionOnCollisionGet
      x-type: one-shot
      summary: Spheroの衝突イベントを取得する。
      description: プラグイン側でキャッシュしている最新のイベントメッセージを1つ取得する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの衝突イベント情報を返す。
            衝突イベント情報の取得に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/CollisionResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              collision:
                impactAxis:
                  x: true
                  'y': false
                impactPower:
                  x: 152
                  'y': 75
                impactSpeed: 0
                impactTimestamp: 1483241696789
                impactTimeStampString: '2015-05-17T10:02:20+09:00'
                impactAcceleration:
                  x: -1.57421875
                  'y': -1.53076171875
                  z: 0
    put:
      operationId: spheroCollisionOnCollisionPut
      x-type: event
      summary: Spheroの衝突イベントの受信を開始する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: formData
          required: true
          type: string
        - name: interval
          description: イベント受信間隔。単位：mSec
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: >-
            Spheroの衝突イベントの開始結果を返す。
            開始に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/CollisionEvent'
        examples:
          application/json:
            serviceId: Host.exampleId.localhost.deviceconnect.org
            profile: sphero
            interface: collision
            attribute: oncollision
            collision:
              impactAxis:
                x: true
                'y': false
              impactPower:
                x: 152
                'y': 75
              impactSpeed: 0
              impactTimeStamp: 1483241696789
              impactTimeStampString: '2015-05-17T10:02:20+09:00'
              impactAcceleration:
                x: -1.57421875
                'y': -1.53076171875
                z: 0
    delete:
      operationId: spheroCollisionOnCollisionDelete
      x-type: event
      summary: Spheroの衝突イベントの受信を停止する。
      description: >-
        スマートデバイスでサポートしていないパラメータがある場合には、
        そのパラメータを省略する。
      parameters:
        - name: serviceId
          description: サービスID。
          in: query
          required: true
          type: string
      responses:
        '200':
          description: >-
            Spheroの衝突イベントの停止結果を返す。
            停止に失敗した場合はエラーを返す。
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
definitions:
  CollisionResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/CollisionInfo'
  CollisionEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/CollisionInfo'
  CollisionInfo:
    type: object
    required:
      - collision
    properties:
      collision:
        type: object
        title: 衝突イベント
        description: 衝突イベントオブジェクト。
        properties:
          impactAcceleration:
            type: object
            title: 衝突加速度
            description: 衝突加速度。
            required:
              - x
              - 'y'
              - z
            properties:
              x:
                type: number
                title: x成分
                description: x軸方向への加速度(cm/s2)
              'y':
                type: number
                title: y成分
                description: y軸方向への加速度(cm/s2)
              z:
                type: number
                title: z成分
                description: z軸方向への加速度(cm/s2)
          impactAxis:
            type: object
            title: 衝突軸
            description: 衝突軸。
            required:
              - x
              - 'y'
            properties:
              x:
                type: boolean
                title: x成分
                description: x成分。
              'y':
                type: boolean
                title: y成分
                description: y成分。
          impactPower:
            type: object
            title: 衝突力
            description: 衝突力。
            required:
              - x
              - 'y'
            properties:
              x:
                type: number
                title: x成分
                description: x成分。
              'y':
                type: number
                title: y成分
                description: y成分。
          impactSpeed:
            type: number
            title: 衝突速度
            description: '衝突速度(単位: cm/s)'
          impactTimeStamp:
            type: integer
            format: int64
            title: 衝突時刻
            description: '衝突した時間のタイムスタンプ(単位: ミリ秒)'
          impactTimeStampString:
            type: string
            format: date-time
            title: 衝突時刻の文字列
            description: >-
              衝突した時間のタイムスタンプを
              RFC3339「yyyy-MM-dd''T''HH:mm:ssZZZZZ」の形式で返す。
  LocatorResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/LocatorInfo'
  LocatorEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/LocatorInfo'
  LocatorInfo:
    type: object
    required:
      - locator
    properties:
      locator:
        type: object
        title: 位置
        description: Spheroの位置座標オブジェクト。
        required:
          - positionX
          - positionY
          - velocityX
          - velocityY
        properties:
          positionX:
            type: number
            title: x座標
            description: '位置のx座標 (単位: cm)'
          positionY:
            type: number
            title: y座標
            description: '位置のy座標 (単位: cm)'
          velocityX:
            type: number
            title: x成分
            description: '速度のx成分 (単位:cm/s)'
          velocityY:
            type: number
            title: y成分
            description: '速度のy成分 (単位:cm/s)'
  QuaternionResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/QuaternionInfo'
  QuaternionEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/QuaternionInfo'
  QuaternionInfo:
    type: object
    required:
      - quaternion
    properties:
      quaternion:
        type: object
        title: 四元数
        description: 四元数オブジェクト。
        required:
          - q0
          - q1
          - q2
          - q3
          - interval
        properties:
          q0:
            type: number
            title: i軸
            description: i軸
          q1:
            type: number
            title: j軸
            description: j軸
          q2:
            type: number
            title: k軸
            description: k軸
          q3:
            type: number
            title: s軸
            description: s軸
          interval:
            type: integer
            format: int64
            title: インターバル
            description: '計測のインターバル。(単位: ミリ秒)'
  EventRegistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  EventUnregistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: >-
          0:正常応答<br>
          0以外:異常応答
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: >-
          レスポンスに対する署名。
          アプリケーション側から事前にHMACキーを共有されていた場合は必須。
  CommonEvent:
    type: object
    required:
      - serviceId
      - profile
      - interface
      - attribute
    properties:
      serviceId:
        type: string
        title: サービスID
        description: イベントを送信したサービスのID
      profile:
        type: string
        title: プロファイル名
        description: プロファイル名。
      interface:
        type: string
        title: インターフェース名
        description: インターフェース名。
      attribute:
        type: string
        title: アトリビュート名
        description: アトリビュート名。
