swagger: '2.0'
basePath: /gotapi/walkState
info:
  title: WalkState Profile
  version: 2.0.0
  description: 歩行状態を通知する機能を提供するプロファイル。
consumes:
  - application/x-www-form-urlencoded
  - multipart/form-data
paths:
  /onWalkState:
    get:
      operationId: walkStateOnWalkStateGet
      x-type: one-shot
      summary: 該当デバイスの歩行状態計測イベントを取得する。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/WalkStateResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
              walk:
                step: 123456
                state: Walking
                speed: 5.799
                distance: 12.3456
                balance: 0.16
                timeStamp: 1483241696789
                timeStampString: '2015-05-17T10:02:20+09:00'
    put:
      operationId: walkStateOnWalkStatePut
      x-type: event
      summary: 該当デバイスの歩行状態計測イベントを通知する。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: formData
          required: true
          type: string
        - name: interval
          description: デバイスプラグインがイベントを送信する間隔。
          in: formData
          required: false
          type: integer
          format: int64
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/EventRegistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
      x-event:
        schema:
          $ref: '#/definitions/WalkStateEvent'
        examples:
          application/json:
            serviceId: Host.dummyId.localhost.deviceconnect.org
            profile: walkstate
            attribute: onwalkstate
            walk:
              step: 123456
              state: Walking
              speed: 5.799
              distance: 12.3456
              balance: 0.16
              timeStamp: 1483241696789
              timeStampString: '2015-05-17T10:02:20+09:00'
    delete:
      operationId: walkStateOnWalkStateDelete
      x-type: event
      summary: 該当デバイスの歩行状態計測イベントを停止する。
      description: ''
      parameters:
        - name: serviceId
          description: サービスID。取得対象スマートデバイス
          in: query
          required: true
          type: string
      responses:
        '200':
          description: ''
          schema:
            $ref: '#/definitions/EventUnregistrationResponse'
          examples:
            application/json:
              result: 0
              product: Example System
              version: 1.0.0
definitions:
  WalkStateResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
      - $ref: '#/definitions/WalkStateInfo'
  WalkStateEvent:
    type: object
    allOf:
      - $ref: '#/definitions/CommonEvent'
      - $ref: '#/definitions/WalkStateInfo'
  WalkStateInfo:
    type: object
    required:
      - walk
    properties:
      walk:
        type: object
        title: 歩行情報
        required:
          - step
          - state
          - speed
          - balance
          - timeStamp
          - timeStampString
        properties:
          step:
            type: number
            format: double
            title: 歩数
            description: 歩数。単位は歩。
          state:
            type: string
            enum:
              - Stop
              - Walking
              - Running
            title: 歩行状態
            description: '<ul><li>Stop:停止</li><li>Walking:歩行</li><li>Running:走行</li></ul>'
          speed:
            type: number
            format: double
            title: 速度
            description: 速度。単位はkm/h。
          distance:
            type: number
            format: double
            title: 距離
            description: 距離。単位はkm。
          balance:
            type: number
            format: double
            title: 左右バランス
            description: 左右のバランス。1に近いほど左右のバランスが良い。<br>-1.0〜1.0
          timeStamp:
            type: integer
            format: int64
            title: タイムスタンプ (Unix時刻)
            description: 測定が行われた測定時間。ミリ秒のUnixタイムスタンプで返す。
          timeStampString:
            type: string
            format: date-time
            title: タイムスタンプ (日付)
            description: 'タイムスタンプと同じタイムスタンプをRFC3339「yyyy-MM-dd''T''HH:mm:ssZZZZZ」の形式で返す。'
  EventRegistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  EventUnregistrationResponse:
    type: object
    allOf:
      - $ref: '#/definitions/CommonResponse'
  CommonResponse:
    type: object
    required:
      - result
      - product
      - version
    properties:
      result:
        type: integer
        title: 処理結果
        description: '0:正常応答<br>0以外:異常応答'
      product:
        type: string
        title: システム名
        description: DeviceConnectシステムの名前。
      version:
        type: string
        title: システムバージョン
        description: DeviceConnectシステムのバージョン名。
      hmac:
        type: string
        title: 署名
        description: レスポンスに対する署名。アプリケーション側から事前にHMACキーを共有されていた場合は必須。
  CommonEvent:
    type: object
    required:
      - serviceId
      - profile
      - interface
      - attribute
    properties:
      serviceId:
        type: string
        title: サービスID
        description: イベントを送信したサービスのID
      profile:
        type: string
        title: プロファイル名
        description: プロファイル名。
      interface:
        type: string
        title: インターフェース名
        description: インターフェース名。
      attribute:
        type: string
        title: アトリビュート名
        description: アトリビュート名。
